services:
    Ibexa\FieldTypeRichText\FieldType\RichText\Type:
        public: true # @todo should be private
        parent: ezpublish.fieldType
        arguments:
            - '@Ibexa\FieldTypeRichText\RichText\InputHandler'
        tags:
            - {name: ezplatform.field_type, alias: ezrichtext}
