services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\FieldTypeRichText\Form\Type\RichTextFieldType:
        arguments:
            $docbookToXhtml5EditConverter: '@ezrichtext.converter.edit.xhtml5'
            $fieldTypeService: '@ezpublish.api.service.field_type'

    Ibexa\FieldTypeRichText\Form\Type\RichTextType:
        arguments:
            $docbookToXhtml5EditConverter: '@ezrichtext.converter.edit.xhtml5'

    Ibexa\FieldTypeRichText\Validator\Constraints\RichTextValidator:
        tags:
            - { name: validator.constraint_validator }

    Ibexa\FieldTypeRichText\Form\Mapper\RichTextFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: ezrichtext }

