services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Ibexa\FieldTypeRichText\FieldType\RichText\RichTextStorage\Gateway\DoctrineStorage:
        arguments:
            - '@ezpublish.fieldType.ezurl.storage_gateway'
            - '@ezpublish.api.storage_engine.legacy.connection'
